version: $(VERSION_NUMBER)-{branch}

pull_requests:
  do_not_increment_build_number: true
clone_folder: c:\projects\MK.WebLib

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(VERSION_NUMBER)
  assembly_file_version: $(VERSION_NUMBER)

before_build:
  - nuget restore

configuration: Release

environment:
  VERSION_NUMBER: 0.2.3.$(APPVEYOR_BUILD_NUMBER)

  COVERALLS_REPO_TOKEN:
    secure: 2Ms497ur1lidXPzesGpHAMTsmQqEDMuavbfkRKfaZiipJGplapYxCckeNJ+hYbUl

build:
  verbosity: minimal

test:
  categories:
    except:
    - skip

artifacts:
- path: bin/Relative/MK.WebLib.dll
  name: MK.WebLib.dll
after_test: 
  - $(APPVEYOR_BUILD_FOLDER)\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:nunit-console -targetargs:"/noshadow /domain:single src\MK.WebLib.T\bin\MK.WebLib.T.dll" -output:coverage.xml
  - $(APPVEYOR_BUILD_FOLDER)\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

notifications:
- provider: Email
  to:
  - maxkoryukov@yandex.ru
  subject: AppVeyor Notification for you, dude
  message: Something changes on AppVeyour https://ci.appveyor.com/project/maxkoryukov/mk-weblib
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true