version: $(MY_VERSION_NUMBER).{build}-{branch}

pull_requests:
  do_not_increment_build_number: true

clone_folder: c:\projects\MK.Lib

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(MY_VERSION_NUMBER).{build}
  assembly_file_version: $(MY_VERSION_NUMBER).{build}

before_build:
  - nuget restore

configuration: Release

environment:
  MY_VERSION_NUMBER: 0.5.0

  COVERALLS_REPO_TOKEN:
    secure: 2Ms497ur1lidXPzesGpHAMTsmQqEDMuavbfkRKfaZiipJGplapYxCckeNJ+hYbUl

build:
  project: MK.Lib.sln
  verbosity: minimal

test:
  # assemblies to test - optional
  assemblies:
    - '**\*.T.exe'
    - '**\*.T.dll'
  categories:
    except:
    - skip

artifacts:
- path: src\MK.Lib\bin\Release\MK.Lib.dll
  name: MK.Lib.dll

after_test:
  - cmd: coverage-calc.bat
  - cmd: coverage-send.bat

deploy:
  release: $(MY_VERSION_NUMBER)
  description: '[![Coverage Status](https://coveralls.io/repos/github/maxkoryukov/MK.Lib/badge.svg?branch=$(MY_VERSION_NUMBER))](https://coveralls.io/github/maxkoryukov/MK.Lib?branch=$(MY_VERSION_NUMBER))

* **ADD INFO FROM CHANGELOG**'
  provider: GitHub
  auth_token:
    secure: cMlMNvFKbCJ4qniAHC5tPYS5xTA0MvGsBgbTc+zykO5I02heS+DFt5d0tcACXbcw
  artifact: MK.Lib.dll
  draft: true
  prerelease: false
  on:
    #branch: master                  # release from master branch only
    appveyor_repo_tag: true         # deploy on tag push only

notifications:
- provider: Email
  to:
  - maxkoryukov@yandex.ru
  subject: AppVeyor Notification for you, dude
  message: Something changes on AppVeyour https://ci.appveyor.com/project/maxkoryukov/mk-lib
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
